In [4]:
# Install BERTopic and dependencies
!pip install bertopic
!pip install sentence-transformers
!pip install umap-learn
!pip install hdbscan

Requirement already satisfied: bertopic in C:\Users\HP\anaconda3\Lib\site-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (2.3.5)
Requirement already satisfied: pandas>=1.1.5 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (2.3.3)
Requirement already satisfied: plotly>=4.7.0 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (6.3.0)
Requirement already satisfied: scikit-learn>=1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (1.7.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (6.1.0)
Requirement already satisfied: tqdm>=4.41.1 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in C:\Users\HP\anaconda3\Lib\site-packages (from bertopic) (0.45.1)
Requirement already satisfied: scipy>=1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\anaconda3\Lib\site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\HP\anaconda3\Lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\HP\anaconda3\Lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\HP\anaconda3\Lib\site-packages (from plotly>=4.7.0->bertopic) (2.7.0)
Requirement already satisfied: packaging in C:\Users\HP\anaconda3\Lib\site-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: six>=1.5 in C:\Users\HP\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from scikit-learn>=1.0->bertopic) (3.5.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (5.20.0)
Requirement already satisfied: tokenizers>=0.19 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (0.23.3)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (1.33.0)
Requirement already satisfied: torch>=2.2 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (2.13.0)
Requirement already satisfied: typing_extensions>=4.10.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: anyio in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (4.10.0)
Requirement already satisfied: certifi in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (2025.11.12)
Requirement already satisfied: httpcore==1.* in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\HP\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (2026.9.29)
Requirement already satisfied: typer in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (0.17.4)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: setuptools>=77.0.3 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers>=0.4.1->bertopic) (84.2.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: colorama in C:\Users\HP\anaconda3\Lib\site-packages (from tqdm>=4.41.1->bertopic) (0.4.6)
Requirement already satisfied: numba>=0.51.2 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.62.1)
Requirement already satisfied: pynndescent>=0.5 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: sniffio>=1.1 in C:\Users\HP\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\HP\anaconda3\Lib\site-packages (from jinja2->torch>=2.2->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\HP\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\HP\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\HP\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\HP\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\HP\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Requirement already satisfied: sentence-transformers in C:\Users\HP\anaconda3\Lib\site-packages (6.1.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (5.20.0)
Requirement already satisfied: tokenizers>=0.19 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (0.23.3)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: numpy>=1.24.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (2.3.5)
Requirement already satisfied: scikit-learn>=1.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\HP\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: anyio in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.10.0)
Requirement already satisfied: certifi in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\HP\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\HP\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.9.29)
Requirement already satisfied: typer in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.17.4)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\HP\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\HP\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools>=77.0.3 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (84.2.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in C:\Users\HP\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\HP\anaconda3\Lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in C:\Users\HP\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\HP\anaconda3\Lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\HP\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\HP\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\HP\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\HP\anaconda3\Lib\site-packages (from rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\HP\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Requirement already satisfied: umap-learn in C:\Users\HP\anaconda3\Lib\site-packages (0.5.12)
Requirement already satisfied: numpy>=1.23 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (2.3.5)
Requirement already satisfied: scipy>=1.3.1 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (1.7.2)
Requirement already satisfied: numba>=0.51.2 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (0.62.1)
Requirement already satisfied: pynndescent>=0.5 in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (0.6.0)
Requirement already satisfied: tqdm in C:\Users\HP\anaconda3\Lib\site-packages (from umap-learn) (4.67.1)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\HP\anaconda3\Lib\site-packages (from numba>=0.51.2->umap-learn) (0.45.1)
Requirement already satisfied: joblib>=0.11 in C:\Users\HP\anaconda3\Lib\site-packages (from pynndescent>=0.5->umap-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from scikit-learn>=1.6->umap-learn) (3.5.0)
Requirement already satisfied: colorama in C:\Users\HP\anaconda3\Lib\site-packages (from tqdm->umap-learn) (0.4.6)
Requirement already satisfied: hdbscan in C:\Users\HP\anaconda3\Lib\site-packages (0.8.44)
Requirement already satisfied: numpy<3,>=1.20 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan) (2.3.5)
Requirement already satisfied: scipy>=1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan) (1.7.2)
Requirement already satisfied: joblib>=1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from hdbscan) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\HP\anaconda3\Lib\site-packages (from scikit-learn>=1.6->hdbscan) (3.5.0)

In [5]:
# Importing required Libraries

import pandas as pd
import numpy as np

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

import matplotlib.pyplot as plt

In [6]:
# Importing cleaned/processed data

cp_df = pd.read_csv(r"C:\Users\HP\OneDrive\Documents\AMDARI\Montra Jupyter\quality_checked.csv")

In [7]:
cp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   review_id           35000 non-null  int64
 1   booking_id          35000 non-null  int64
 2   guest_id            35000 non-null  int64
 3   hotel_id            35000 non-null  int64
 4   review_text         35000 non-null  object
 5   rating_score        35000 non-null  float64
 6   review_date         35000 non-null  object
 7   sentiment_label     35000 non-null  object
 8   room_type           35000 non-null  object
 9   booking_channel     35000 non-null  object
 10  check_in_date       35000 non-null  object
 11  check_out_date      35000 non-null  object
 12  total_amount        35000 non-null  float64
 13  stay_duration       35000 non-null  int64
 14  customer_type       35000 non-null  object
 15  loyalty_status      35000 non-null  object
 16  country             35000 non-null  object
 17  previous_stays      35000 non-null  int64
 18  hotel_name          35000 non-null  object
 19  location            35000 non-null  object
 20  star_rating         35000 non-null  int64
 21  total_rooms         35000 non-null  int64
 22  clean_review        35000 non-null  object
 23  sentiment_encoded   35000 non-null  int64
 24  word_count          35000 non-null  int64
 25  char_count          35000 non-null  int64
 26  stay_duration_calc  35000 non-null  int64
 27  price_per_night     35000 non-null  float64
 28  expected_sentiment  35000 non-null  object
 29  derived_sentiment   35000 non-null  object
dtypes: float64(3), int64(12), object(15)
memory usage: 8.0+ MB

In [8]:
cp_df.columns

Index(['review_id', 'booking_id', 'guest_id', 'hotel_id', 'review_text',
       'rating_score', 'review_date', 'sentiment_label', 'room_type',
       'booking_channel', 'check_in_date', 'check_out_date', 'total_amount',
       'stay_duration', 'customer_type', 'loyalty_status', 'country',
       'previous_stays', 'hotel_name', 'location', 'star_rating',
       'total_rooms', 'clean_review', 'sentiment_encoded', 'word_count',
       'char_count', 'stay_duration_calc', 'price_per_night',
       'expected_sentiment', 'derived_sentiment'],
      dtype='object')

In [9]:
# Check dataframe structure
cp_df.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label,room_type,booking_channel,...,star_rating,total_rooms,clean_review,sentiment_encoded,word_count,char_count,stay_duration_calc,price_per_night,expected_sentiment,derived_sentiment
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral,Suite,Direct Website,...,4,118,the overall price be fair for what we pay migh...,0,11,51,1,296.44,neutral,neutral
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive,Deluxe,Corporate Portal,...,4,95,the room be nothing out of the ordinary for wh...,1,28,148,4,120.89,positive,positive
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative,Executive,Travel Agent,...,4,231,unfortunately the pool be outdate it clearly n...,-1,16,93,2,207.80,negative,negative
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,neutral,Family Room,Airbnb,...,3,101,we be disappoint that the neighborhood be disa...,-1,21,118,3,200.39,neutral,neutral
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral,Deluxe,Expedia,...,4,214,the room service be standard hotel fare for wh...,0,39,184,5,120.77,neutral,neutral

In [10]:
# Ensure no missing reviews
cp_df = cp_df.dropna(subset=['clean_review'])

# Remove exact duplicate reviews
cp_df_clean = cp_df.drop_duplicates(subset=["clean_review"])

# Convert reviews to list format
reviews = cp_df_clean['clean_review'].astype(str).tolist()

print(f"Number of reviews: {len(reviews)}")
print("Original:", len(cp_df))
print("After deduplication:", len(cp_df_clean))
reviews [:3]

Number of reviews: 34498
Original: 35000
After deduplication: 34498

['the overall price be fair for what we pay might not',
 'the room be nothing out of the ordinary for what we pay the overall price exceed our expectation a great deal and the quality easily match the price',
 'unfortunately the pool be outdate it clearly need some upkeep would not recommend it to other']

In [11]:
import re

uk_cities = ['london', 'manchester', 'birmingham', 'leeds', 'bristol', 'liverpool', 'glasgow', 'oxford', 'bath', 'york', 'cardiff', 'nottingham', 'brighton', sheffield', 'leicester', 'belfast', 'southampton', 'aberdeen']
city_pattern = re.compile(r'\b('+'|'.join(uk_cities) + R')\b, re.IGNORECASE)
reviews = [city_pattern.sub(' ',doc).strip() for doc in reviews)
reviews = [re.sub(r'\s+', ' ',doc) for doc in reviews

In [12]:
from collections import Counter
import torch

In [13]:
# Normalize reviews
rev_norm = [doc.lower().strip() for doc in reviews]

# Count exact duplicates
total_rev = len(rev_norm)
unique_rev = len(set(rev_norm))
duplicated_rev = total_rev - unique_rev

print(f'Total reviews: {total_rev}')
print(f'Unique reviews: {unique_rev}')
print(f'Duplicate document: {duplicated_rev}')

if total_rev > 0:
    duplicated_rate = duplicated_rev/total_rev *100
    print(f'Duplicate rate: {duplicated_rate:.2f}%')

Total reviews: 34498
Unique reviews: 34498
Duplicate document: 0
Duplicate rate: 0.00%

In [14]:
# Calculate Vocabulary Size
all_word = " ".join(rev_norm).split()
print(f'vocab_size: {len(set(all_word))}')

# Display first 20 common words
print(Counter(all_word).most_common(20))

vocab_size: 496
[('the', 72877), ('be', 71883), ('our', 23803), ('in', 23541), ('we', 23504), ('to', 18616), ('for', 18203), ('a', 17544), ('that', 16097), ('overall', 12006), ('pay', 10935), ('stay', 10933), ('as', 10835), ('out', 10519), ('i', 10055), ('on', 10042), ('and', 9984), ('of', 9732), ('hotel', 9724), ('nothing', 9344)]

##### Generating Sentence Embeding

In [15]:
# Load embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
embeddings = embedding_model.encode(
    reviews,
    show_progress_bar=True
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1079 [00:00<?, ?it/s]

In [16]:
embeddings[:3]

array([[-0.01264704, -0.00673828,  0.02616902, ..., -0.17582549,
         0.00824867,  0.02769971],
       [ 0.0522748 , -0.0024588 ,  0.00135637, ..., -0.01036991,
        -0.08671826,  0.07271781],
       [-0.04229411,  0.03272924,  0.02205706, ..., -0.03831463,
        -0.02556697,  0.0941811 ]], shape=(3, 384), dtype=float32)

In [17]:
embeddings.shape

(34498, 384)

In [18]:
# Configure the UMAP
import umap

umap_model = umap.UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)

In [19]:
# Configure the hdbscan
import hdbscan

hdbscan_model = hdbscan.HDBSCAN(
    min_cluster_size=800,
    min_samples=100,
    metric='euclidean',
    prediction_data=True
)

In [20]:
# Configure the CountVectorizer

from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    stop_words='english',
    ngram_range=(1, 5),
    min_df=5
)

##### Training BERTopic Model

In [21]:
# Initialize BERTopic
topic_model = BERTopic(
    embedding_model = embedding_model,
    umap_model = umap_model,
    hdbscan_model = hdbscan_model,
    vectorizer_model = vectorizer_model,
    #language="english",
    calculate_probabilities=True,
    verbose=True
)

print(topic_model.vectorizer_model)

# Fit model
topics, probabilities = topic_model.fit_transform(
    reviews,
    embeddings
)

print(topic_model.vectorizer_model)

2026-10-20 17:19:01,993 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

CountVectorizer(min_df=5, ngram_range=(1, 5), stop_words='english')

2026-10-20 17:20:05,255 - BERTopic - Dimensionality - Completed ✓
2026-10-20 17:20:05,258 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-10-20 17:20:13,673 - BERTopic - Cluster - Completed ✓
2026-10-20 17:20:13,682 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-10-20 17:20:16,127 - BERTopic - Representation - Completed ✓

CountVectorizer(min_df=5, ngram_range=(1, 5), stop_words='english')

In [22]:
topic_model.reduce_topics(reviews, nr_topics = 'auto')

2026-10-20 17:20:16,555 - BERTopic - Topic reduction - Reducing number of topics
2026-10-20 17:20:16,576 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-10-20 17:20:19,300 - BERTopic - Representation - Completed ✓
2026-10-20 17:20:19,308 - BERTopic - Topic reduction - Reduced number of topics from 13 to 13

##### Add Topic information to data frame

In [23]:
# Assign topic labels
cp_df_clean['Topic'] = topics

# Optional: assign topic probability
cp_df_clean['Topic_Probability'] = probabilities.max(axis=1).round(2)

cp_df_clean.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label,room_type,booking_channel,...,clean_review,sentiment_encoded,word_count,char_count,stay_duration_calc,price_per_night,expected_sentiment,derived_sentiment,Topic,Topic_Probability
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral,Suite,Direct Website,...,the overall price be fair for what we pay migh...,0,11,51,1,296.44,neutral,neutral,0,0.49
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive,Deluxe,Corporate Portal,...,the room be nothing out of the ordinary for wh...,1,28,148,4,120.89,positive,positive,0,0.39
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative,Executive,Travel Agent,...,unfortunately the pool be outdate it clearly n...,-1,16,93,2,207.80,negative,negative,6,1.00
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,neutral,Family Room,Airbnb,...,we be disappoint that the neighborhood be disa...,-1,21,118,3,200.39,neutral,neutral,0,0.83
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral,Deluxe,Expedia,...,the room service be standard hotel fare for wh...,0,39,184,5,120.77,neutral,neutral,0,0.11

##### View discovered topics

In [24]:
# Topic summary
topic_info = topic_model.get_topic_info()

topic_info.head(20)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1661,-1_spa_receptionist_overall_pay,"[spa, receptionist, overall, pay, clearly, ite...",[the restaurant leave a lot to be desire sever...
1,0,9403,0_overall_pay_check_hotel,"[overall, pay, check, hotel, staff, arrival, s...",[overall our arrival experience be acceptable ...
2,1,9089,1_time_hotel_stay_fine,"[time, hotel, stay, fine, glasgow, visit, over...",[this hotel be a fine if unremarkable choice f...
3,2,3586,2_buffet_option_cafe_house cafe,"[buffet, option, cafe, house cafe, house, dini...",[arrival be unremarkable I would describe the ...
4,3,1950,3_gym_fitness_fitness facility_facility,"[gym, fitness, fitness facility, facility, pay...","[the fitness facility be standard, the fitness..."
5,4,1596,4_belfast_stay belfast_visit belfast_hotel,"[belfast, stay belfast, visit belfast, hotel, ...",[this hotel be a fine if unremarkable choice f...
6,5,1419,5_bathroom_bathroom area_area_clean,"[bathroom, bathroom area, area, clean, leave, ...",[sadly the pricing turn out to be not worth wh...
7,6,1147,6_pool_overall pool_stay_overall,"[pool, overall pool, stay, overall, pay, fine,...",[the rate we pay be also the pool be basic but...
8,7,1081,7_fi_wi_wi fi_overall wi fi,"[fi, wi, wi fi, overall wi fi, overall wi, sta...",[the neighborhood be fine on top of that the w...
9,8,984,8_base_ask base_base visit_ask base visit,"[base, ask base, base visit, ask base visit, a...",[we could not have ask for a well base while v...
10,9,939,9_carpet_clean_overall carpet_pay,"[carpet, clean, overall carpet, pay, stay, ove...",[the carpet be reasonably clean for what we pa...
11,10,826,10_breakfast_overall breakfast_overall_pay,"[breakfast, overall breakfast, overall, pay, b...","[the breakfast be decent, the breakfast be acc..."
12,11,817,11_lounge_overall lounge_overall_pay,"[lounge, overall lounge, overall, pay, lounge ...","[the lounge be adequate might not, the lounge ..."

##### Examine Keywords for each topic

In [25]:
# Display top words for each topic
for topic in topic_info['Topic'][:10]:
    
    if topic != -1:
        print(f"\nTopic {topic}")
        print(topic_model.get_topic(topic))

Topic 0
[('overall', np.float64(0.025465436528728937)), ('pay', np.float64(0.022480419992551553)), ('check', np.float64(0.017449504216692596)), ('hotel', np.float64(0.017047733166089856)), ('staff', np.float64(0.015997281214049322)), ('arrival', np.float64(0.015494139176688857)), ('stay', np.float64(0.014705475262775585)), ('price', np.float64(0.01443339407245609)), ('desk', np.float64(0.014094934802053453)), ('area', np.float64(0.013077241097545341))]

Topic 1
[('time', np.float64(0.03083297043552961)), ('hotel', np.float64(0.029127633808733806)), ('stay', np.float64(0.02750613989411188)), ('fine', np.float64(0.020251282422249085)), ('glasgow', np.float64(0.018585831443820054)), ('visit', np.float64(0.018192686661391278)), ('overall', np.float64(0.017692964394137374)), ('pay', np.float64(0.0169575623740117)), ('unremarkable', np.float64(0.01651572232870435)), ('stand', np.float64(0.016156856300037967))]

Topic 2
[('buffet', np.float64(0.025182466967611634)), ('option', np.float64(0.02145660976928915)), ('cafe', np.float64(0.02108860923929101)), ('house cafe', np.float64(0.02108860923929101)), ('house', np.float64(0.02108860923929101)), ('dining', np.float64(0.020996009983932955)), ('dining option', np.float64(0.020996009983932955)), ('restaurant', np.float64(0.020828279338450873)), ('business', np.float64(0.02071217419290651)), ('business center', np.float64(0.02058015667673888))]

Topic 3
[('gym', np.float64(0.06270081633658937)), ('fitness', np.float64(0.05368757612072099)), ('fitness facility', np.float64(0.05368757612072099)), ('facility', np.float64(0.05368757612072099)), ('pay', np.float64(0.02012205850707528)), ('overall', np.float64(0.02005386203927326)), ('fine', np.float64(0.019797012531535294)), ('stay', np.float64(0.01865939867837704)), ('need', np.float64(0.018132721036247156)), ('functional', np.float64(0.014999429710883316))]

Topic 4
[('belfast', np.float64(0.11075484781847462)), ('stay belfast', np.float64(0.042175930277419116)), ('visit belfast', np.float64(0.039119727021184075)), ('hotel', np.float64(0.029315563656808437)), ('time', np.float64(0.028937626686417202)), ('stay', np.float64(0.028265279983668904)), ('visit', np.float64(0.02360904383974142)), ('fine', np.float64(0.020628979523497074)), ('overall', np.float64(0.018109357270888873)), ('pay', np.float64(0.018003583082427776))]

Topic 5
[('bathroom', np.float64(0.0872653160001839)), ('bathroom area', np.float64(0.047449992016349)), ('area', np.float64(0.04012848431871318)), ('clean', np.float64(0.027940760523337927)), ('leave', np.float64(0.01896035749873152)), ('overall', np.float64(0.018867825277218798)), ('stain', np.float64(0.01859866266706529)), ('pay', np.float64(0.0183371563965049)), ('leave lot desire', np.float64(0.01793608252875448)), ('lot desire', np.float64(0.01793608252875448))]

Topic 6
[('pool', np.float64(0.12593141260629928)), ('overall pool', np.float64(0.02562971038438589)), ('stay', np.float64(0.022516801336197656)), ('overall', np.float64(0.022032875696436992)), ('pay', np.float64(0.02159385964692111)), ('fine', np.float64(0.021520725409091807)), ('need', np.float64(0.020769741073093338)), ('pool standard', np.float64(0.02042783520218727)), ('pool fine need', np.float64(0.020167518572065616)), ('pool fine', np.float64(0.020167518572065616))]

Topic 7
[('fi', np.float64(0.11556739898042252)), ('wi', np.float64(0.11556739898042252)), ('wi fi', np.float64(0.11556739898042252)), ('overall wi fi', np.float64(0.018992270957425738)), ('overall wi', np.float64(0.018992270957425738)), ('stay', np.float64(0.018835701522186377)), ('overall', np.float64(0.01831345212102984)), ('pay', np.float64(0.017831346762151146)), ('wi fi adequate', np.float64(0.01715031837989775)), ('fi adequate', np.float64(0.01715031837989775))]

Topic 8
[('base', np.float64(0.11820674292144329)), ('ask base', np.float64(0.11820674292144329)), ('base visit', np.float64(0.11820674292144329)), ('ask base visit', np.float64(0.11820674292144329)), ('ask', np.float64(0.10919002962379548)), ('visit', np.float64(0.08661118606863402)), ('genuinely', np.float64(0.024742130788232765)), ('visit london', np.float64(0.023632199225711293)), ('honestly', np.float64(0.022848191611139903)), ('impressed', np.float64(0.02130294563112709))]

##### Retrieving Representative Reviews Per Topic

In [26]:
representative_docs = topic_model.get_representative_docs()

for topic, docs in representative_docs.items():
    
    print(f"\n{'='*60}")
    print(f"TOPIC {topic}")
    
    for doc in docs[:3]:
        print(f"- {doc}")

============================================================
TOPIC -1
- the restaurant leave a lot to be desire several item be clearly reheat in addition we be disappoint that the check in desk be chaotic
- we be disappoint that the manager be dismissive that say the room service leave a lot to be desire several item be clearly reheat
- the dining option leave a lot to be desire several item be clearly reheat leave feel pretty disappointed overall

============================================================
TOPIC 0
- overall our arrival experience be acceptable also overall the neighborhood be not the most convenient but manageable meanwhile the front desk team be okay overall
- arrival leave a lot to be desire our room be not ready despite an on time arrival meanwhile the overall price leave a lot to be desire several amenity cost extra on top of the rate leave feel pretty disappointed overall
- overall our arrival experience be about average also I would describe the rate we pay as in line with similar hotel it match what similar hotel charge

============================================================
TOPIC 1
- this hotel be a fine if unremarkable choice for our time in edinburgh also the rate we pay be fair might not
- this hotel be a fine if unremarkable choice for our time in glasgow that say overall get around from the hotel be fine
- this hotel be a fine if unremarkable choice for our time in brighton the check in process be acceptable

============================================================
TOPIC 2
- arrival be unremarkable I would describe the in house cafe as standard hotel fare there be not much variety but it be edible
- I would describe the dining option as fine it cover the basic fine plus overall the business center be adequate an okay option if nothing else be available
- I would describe the in house cafe as decent there be not much variety but it be edible fine for a business trip nothing more

============================================================
TOPIC 3
- the fitness facility be standard
- the fitness facility be adequate might not
- the fitness facility be adequate for what we pay on top of that the fitness facility be nothing special

============================================================
TOPIC 4
- this hotel be a fine if unremarkable choice for our time in belfast plus the carpet be nothing out of the ordinary for what we pay
- this hotel be a fine if unremarkable choice for our time in belfast meanwhile get around from the hotel be acceptable for what we pay
- this hotel be a fine if unremarkable choice for our time in belfast on the other hand the wi fi be fine for our need

============================================================
TOPIC 5
- sadly the pricing turn out to be not worth what we pay on the other hand the bathroom area leave a lot to be desire there be stain we have to point out to staff
- our stay in london do not go as plan plus the bathroom area leave a lot to be desire we find dust on the shelf
- the bathroom area leave a lot to be desire we find dust on the shelf not sure we would come back

============================================================
TOPIC 6
- the rate we pay be also the pool be basic but functional
- the pool be fine for our need for what we pay
- the pool be adequate for what we pay might not on the other hand the pool be fine for our need

============================================================
TOPIC 7
- the neighborhood be fine on top of that the wi fi be nothing special for what we pay
- overall the wi fi be standard might not
- overall the wi fi be adequate

============================================================
TOPIC 8
- we could not have ask for a well base while visit leed the rate we pay be reasonable enough
- we could not have ask for a well base while visit liverpool in addition arrival be about average
- we could not have ask for a well base while visit liverpool overall the pricing be

============================================================
TOPIC 9
- the carpet be reasonably clean for what we pay
- overall the carpet be reasonably clean the manager be adequate
- the neighborhood be fine on top of that the carpet be passably clean

============================================================
TOPIC 10
- the breakfast be decent
- the breakfast be acceptable
- the breakfast be fine

============================================================
TOPIC 11
- the lounge be adequate might not
- the lounge be standard for what we pay in addition overall the lounge be fine for our need
- overall the lounge be nothing special

In [27]:
topic_model.visualize_barchart(top_n_topics=12)

In [28]:
topic_model.visualize_topics()

In [29]:
topic_model.visualize_hierarchy()

In [30]:
topic_model.visualize_heatmap()

In [31]:
custom_labels = topic_model.generate_topic_labels()

topic_model.set_topic_labels(custom_labels)

topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,1661,-1_spa_receptionist_overall_pay,-1_spa_receptionist_overall,"[spa, receptionist, overall, pay, clearly, ite...",[the restaurant leave a lot to be desire sever...
1,0,9403,0_overall_pay_check_hotel,0_overall_pay_check,"[overall, pay, check, hotel, staff, arrival, s...",[overall our arrival experience be acceptable ...
2,1,9089,1_time_hotel_stay_fine,1_time_hotel_stay,"[time, hotel, stay, fine, glasgow, visit, over...",[this hotel be a fine if unremarkable choice f...
3,2,3586,2_buffet_option_cafe_house cafe,2_buffet_option_cafe,"[buffet, option, cafe, house cafe, house, dini...",[arrival be unremarkable I would describe the ...
4,3,1950,3_gym_fitness_fitness facility_facility,3_gym_fitness_fitness facility,"[gym, fitness, fitness facility, facility, pay...","[the fitness facility be standard, the fitness..."
5,4,1596,4_belfast_stay belfast_visit belfast_hotel,4_belfast_stay belfast_visit belfast,"[belfast, stay belfast, visit belfast, hotel, ...",[this hotel be a fine if unremarkable choice f...
6,5,1419,5_bathroom_bathroom area_area_clean,5_bathroom_bathroom area_area,"[bathroom, bathroom area, area, clean, leave, ...",[sadly the pricing turn out to be not worth wh...
7,6,1147,6_pool_overall pool_stay_overall,6_pool_overall pool_stay,"[pool, overall pool, stay, overall, pay, fine,...",[the rate we pay be also the pool be basic but...
8,7,1081,7_fi_wi_wi fi_overall wi fi,7_fi_wi_wi fi,"[fi, wi, wi fi, overall wi fi, overall wi, sta...",[the neighborhood be fine on top of that the w...
9,8,984,8_base_ask base_base visit_ask base visit,8_base_ask base_base visit,"[base, ask base, base visit, ask base visit, a...",[we could not have ask for a well base while v...
10,9,939,9_carpet_clean_overall carpet_pay,9_carpet_clean_overall carpet,"[carpet, clean, overall carpet, pay, stay, ove...",[the carpet be reasonably clean for what we pa...
11,10,826,10_breakfast_overall breakfast_overall_pay,10_breakfast_overall breakfast_overall,"[breakfast, overall breakfast, overall, pay, b...","[the breakfast be decent, the breakfast be acc..."
12,11,817,11_lounge_overall lounge_overall_pay,11_lounge_overall lounge_overall,"[lounge, overall lounge, overall, pay, lounge ...","[the lounge be adequate might not, the lounge ..."

In [32]:
topic_df= cp_df_clean

In [33]:
# Save topic assignments

topic_df = cp_df_clean
topic_df.to_csv(
    'reviews_with_topics.csv',
    index=False
)

# Save topic summary
topic_info.to_csv(
    'topic_summary.csv',
    index=False
)

In [34]:
topic_distribution = (
    topic_df['Topic']
    .value_counts(normalize=True)
    .reset_index()
)

topic_distribution.columns = [
    'Topic',
    'Percentage'
]

topic_distribution['Percentage'] *= 100

topic_distribution.sort_values(
    by='Percentage',
    ascending=False,
    inplace=True
)

topic_distribution.head(10)

   Topic  Percentage
0      0   27.256653
1      1   26.346455
2      2   10.394805
3      3    5.652502
4     -1    4.814772
5      4    4.626355
6      5    4.113282
7      6    3.324830
8      7    3.133515
9      8    2.852339

In [35]:
top_topics = topic_model.get_topic_info().head(10)

print(top_topics[['Topic', 'Count', 'Name']])

   Topic  Count                                        Name
0     -1   1661             -1_spa_receptionist_overall_pay
1      0   9403                   0_overall_pay_check_hotel
2      1   9089                      1_time_hotel_stay_fine
3      2   3586             2_buffet_option_cafe_house cafe
4      3   1950     3_gym_fitness_fitness facility_facility
5      4   1596  4_belfast_stay belfast_visit belfast_hotel
6      5   1419         5_bathroom_bathroom area_area_clean
7      6   1147            6_pool_overall pool_stay_overall
8      7   1081                 7_fi_wi_wi fi_overall wi fi
9      8    984   8_base_ask base_base visit_ask base visit